### ISSUE TITLE
Support for PR's from forks!

### ISSUE THREAD

**Issue by shravanngoswamii** [parkerbxyz/suggest-changes#33]
I know currently this workflow only supports `pull_request` events, but it would much better if this can support `pull_request_target` event too because most PR's usually from contributor's fork! Is there any chance this will be added any soon?

This is what I get now when I used it on `pull_request_target` event.
```
Run parkerbxyz/suggest-changes@v1
  with:
    comment: If this PR is not intended to update any previous release, please update the VERSION file to the latest version.
    token: ***
file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:53811
      const error = new RequestError(toErrorMessage(data), status, {
                    ^
RequestError [HttpError]: Resource not accessible by integration - https://docs.github.com/rest/pulls/reviews#create-a-review-for-a-pull-request
    at file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:53811:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:53128:3 {
  status: 403,
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/shravanngoswamii/docs/pulls/62/reviews',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'suggest-changes octokit-core.js/6.1.2 Node.js/20.13.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"event":"REQUEST_CHANGES","body":"If this PR is not intended to update any previous release, please update the VERSION file to the latest version.","comments":[{"path":"VERSION","line":1,"body":"````suggestion\\nv0.33.0\\n````"}]}',
    request: {
      fetch: [AsyncFunction: customFetch],
      hook: [Function: bound bound register]
    }
  },
  response: {
    url: 'https://api.github.com/repos/shravanngoswamii/docs/pulls/62/reviews',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Sat, 29 Jun 2024 23:48:04 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'istio-envoy',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-github-permissions': 'pull_requests=write',
      'x-content-type-options': 'nosniff',
      'x-envoy-upstream-service-time': '94',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '880B:229AB2:3B4D521:6945897:66809D34',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4992',
      'x-ratelimit-reset': '1719708408',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '8',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/pulls/reviews#create-a-review-for-a-pull-request',
      status: '403'
    }
  }
}
Node.js v20.13.1
```

**Comment by parkerbxyz** [comment]
> Resource not accessible by integration

This appears to be a [GITHUB_TOKEN permissions](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token) issue. Can you try adding the following to the job that runs this action?

```yml
permissions:
  pull-requests: write
```

**Comment by echoix** [comment]
> > Resource not accessible by integration
> 
> This appears to be a [GITHUB_TOKEN permissions](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token) issue. Try adding the following to the job that runs this action:
> 
> ```yml
> permissions:
>   pull-requests: write
> ```
> 
> Let me know if that does the trick! 

A PR from a fork are limited up to a read permission and can't get more. See the link from https://github.com/parkerbxyz/suggest-changes/issues/15#issuecomment-2041171095

I understand it to be a way to protect users from doing the wrong thing that would cause a security vulnerability.

**Comment by parkerbxyz** [comment]
> A PR from a fork are limited up to a read permission and can't get more.

The OP specifically asked about using `pull_request_target`, which I think should work if the permissions are specified as they are in [my example above](https://github.com/parkerbxyz/suggest-changes/issues/33#issuecomment-2322045365). 

From [the documentation](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token):

> When a workflow is triggered by the [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) event, the GITHUB_TOKEN is granted read/write repository permission, even when it is triggered from a public fork. For more information, see "[Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)."

Please also be aware of the following: 

> [!WARNING]
> For workflows that are triggered by the `pull_request_target` event, the `GITHUB_TOKEN` is granted read/write repository permission unless the `permissions` key is specified and the workflow can access secrets, even when it is triggered from a fork. Although the workflow runs in the context of the base of the pull request, you should make sure that you do not check out, build, or run untrusted code from the pull request with this event. Additionally, any caches share the same scope as the base branch. To help prevent cache poisoning, you should not save the cache if there is a possibility that the cache contents were altered. For more information, see "[Keeping your GitHub Actions and workflows secure: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests)" on the GitHub Security Lab website.

Another option is to use a GitHub App token: https://github.com/parkerbxyz/suggest-changes/issues/15#issuecomment-2041263840.

**Comment by maleadt** [comment]
For other people running into this: The `googleapis/code-suggester` does support `pull_request_target`.
